/* File generated with Shader Minifier 1.1.3
 * http://www.ctrl-alt-test.fr
 */
#ifndef SHADER_CODER_INTRO_H_
# define SHADER_CODER_INTRO_H_

const char *tv_vs_glsl =
 "varying vec2 pos;"
 "void main()"
 "{"
   "pos=-((gl_Vertex-1.)*.5),gl_Position=gl_Vertex;"
 "}";

const char *tv_fs_glsl =
 "uniform sampler2D input0;"
 "uniform vec2 viewportSize;"
 "varying vec2 pos;"
 "uniform float fTime,fFlashAmount,fReflectionSize,fDeformValue,fScreenSize1,fScreenSize2,fScreenSize3;"
 "const float v=3.14159;"
 "float f=v/fDeformValue,i=viewportSize.x,y=viewportSize.y;"
 "vec2 s(in vec2 i,in float y)"
 "{"
   "float s=1.5-(y*cos(i.x*v/f)+y*cos(i.y*v/f));"
   "return vec2(i.x*s-.5,i.y*s-.5);"
 "}"
 "vec3 n(in sampler2D i,in vec2 f)"
 "{"
   "return f.x<-1.||f.x>0.||f.y<-1.||f.y>0.?vec3(0.,0.,0.):texture2D(i,f).xyz;"
 "}"
 "float n(in vec2 i)"
 "{"
   "return fract(sin(dot(i.xy,vec2(12.9898,78.233)))*43758.5);"
 "}"
 "void main()"
 "{"
   "vec2 e=vec2(0.,0.);"
   "e.x=1.-pos.x*2.;"
   "e.y=1.-pos.y*2.;"
   "vec2 x=pos,g=s(e,fScreenSize1),r=s(e,fScreenSize2),z=s(e,fScreenSize3);"
   "float c=(2.-cos(v/f/2.+g.x*v/f)-cos(v/f/2.+g.y*v/f))*32.,t=n(vec2(e.x+fTime,e.y-fTime)),d=n(vec2(e.x-fTime,e.y+fTime)),p=t*2./float(i);"
   "vec3 m=n(input0,g),o=n(input0,r),l=n(input0,z);"
   "float a=fReflectionSize*c;"
   "vec3 u;"
   "u.x=n(input0,vec2(g.x-p-a,g.y-p)).x;"
   "u.y=n(input0,vec2(g.x,g.y)).y;"
   "u.z=n(input0,vec2(g.x-p+a,g.y-p)).z;"
   "vec3 S=m+o*o+l*.1+u*.15;"
   "S+=fFlashAmount;"
   "S-=(vec3(t,t,t)-vec3(d,d,d))*.125;"
   "S*=.75+.25*sin(g.x*float(i)*10.2);"
   "S*=.9+.1*cos(g.y*float(y)*10.2)*sin(.5+g.x*float(i)*10.2);"
   "S*=.975+.025*sin(fTime*77.7*cos(fTime*191.1));"
   "gl_FragColor=vec4(S,1.);"
   "return;"
 "}";

const char *terrainTest_vert =
 "varying vec3 cameraPosition,viewDirection;"
 "uniform mat4 modelviewMatrix,imvm;"
 "varying mat4 pmat,mview,mviewproj;"
 "void main()"
 "{"
   "gl_Position=gl_Vertex;"
   "vec4 v=gl_Vertex;"
   "v=gl_ProjectionMatrixInverse*v;"
   "v/=v.w;"
   "v=gl_ModelViewMatrixInverse*v;"
   "vec4 i=v/v.w;"
   "mview=gl_ModelViewMatrix;"
   "mviewproj=gl_ModelViewProjectionMatrix;"
   "pmat=gl_ProjectionMatrix;"
   "cameraPosition=(gl_ModelViewMatrixInverse*vec4(0.,0.,0.,1.)).xyz;"
   "viewDirection=normalize(i-cameraPosition).xyz;"
 "}";

const char *terrainTest_frag =
 "varying vec2 uv;"
 "uniform float iGlobalTime;"
 "uniform sampler2D iChannel0,iChannel1,iChannel2;"
 "varying mat4 mview;"
 "varying float znear,zfar,nearPlane,farPlane;"
 "uniform mat4 mvm,imvm;"
 "varying mat4 pmat;"
 "uniform vec3 cube;"
 "varying vec3 cameraPosition;"
 "varying float nearPlanePosition;"
 "varying vec3 viewDirection;"
 "varying mat4 mviewproj;\n"
 "#define pi2 6.28318530718\n"
 "const float v=.015;"
 "vec2 m=vec2(800.,600.);struct hitInfo{int materialId;};"
 "float i(float v)"
 "{"
   "return fract(sin(v)*43758.5);"
 "}"
 "float n(in vec3 v)"
 "{"
   "vec3 m=floor(v),y=fract(v);"
   "\n#if 0\n"
   "y=y*y*(3.-2.*y);"
   "float z=m.x+m.y*57.+113.*m.z;"
   "return mix(mix(mix(i(z),i(z+1.),y.x),mix(i(z+57.),i(z+58.),y.x),y.y),mix(mix(i(z+113.),i(z+114.),y.x),mix(i(z+170.),i(z+171.),y.x),y.y),y.z);"
 "}"
 "const mat3 s=mat3(0.,.8,.6,-.8,.36,-.48,-.6,-.48,.64);"
 "float p(in vec2 v)"
 "{"
   "vec2 m=floor(v),y=fract(v),i=m.xy+y.xy*y.xy*(3.-2.*y.xy);"
   "return-1.+2.*texture2D(iChannel0,(i+.5)/256.,-100.).x;"
 "}"
 "vec3 i(sampler2D v,vec3 m,vec3 i)"
 "{"
   "vec3 y=texture2D(v,m.yz).xyz,z=texture2D(v,m.zx).xyz,f=texture2D(v,m.xy).xyz;"
   "return y*abs(i.x)+z*abs(i.y)+f*abs(i.z);"
 "}"
 "float f(vec3 v)"
 "{"
   "float f;"
   "f=.5*p(v);"
   "v=s*v*2.02;"
   "f+=.25*p(v);"
   "v=s*v*2.03;"
   "f+=.125*p(v);"
   "v=s*v*2.01;"
   "f+=.0625*p(v);"
   "return f;"
 "}"
 "mat3 x(in float v)"
 "{"
   "float i=cos(v),y=sin(v);"
   "return mat3(i,y,0.,-y,i,0.,0.,0.,1.);"
 "}"
 "mat3 t(in float v)"
 "{"
   "float y=cos(v),z=sin(v);"
   "return mat3(1.,0.,0.,0.,y,-z,0.,z,y);"
 "}"
 "mat3 M(in float v)"
 "{"
   "float y=cos(v),z=sin(v);"
   "return mat3(y,0.,z,0.,1.,0.,-z,0.,y);"
 "}"
 "vec2 M(vec2 v,vec2 y)"
 "{"
   "return v.x<y.x?v:y;"
 "}"
 "float f(float v,float y)"
 "{"
   "return max(-y,v);"
 "}"
 "vec3 i(vec3 v,vec3 y)"
 "{"
   "return mod(v,y)-.5*y;"
 "}"
 "float D(vec2 v)"
 "{"
   "return sqrt(v.x*v.x+v.y*v.y);"
 "}"
 "float e(vec2 v)"
 "{"
   "return v=v*v*v,v=v*v,pow(v.x+v.y,1./6.);"
 "}"
 "float w(vec2 v)"
 "{"
   "return v=v*v,v=v*v,v=v*v,pow(v.x+v.y,.125);"
 "}"
 "float D(vec3 v,vec2 y)"
 "{"
   "vec2 i=vec2(D(v.xz)-y.x,v.y);"
   "return w(i)-y.y;"
 "}"
 "float e(vec3 v,vec2 y)"
 "{"
   "return max(length(v.xz)-y.x,abs(v.y)-y.y);"
 "}"
 "float D(vec3 v,vec3 y,float m)"
 "{"
   "return length(max(abs(v)-y,0.))-m;"
 "}"
 "float n(vec3 v,vec3 y)"
 "{"
   "vec3 i=abs(v)-y;"
   "return min(max(i.x,max(i.y,i.z)),0.)+length(max(i,0.));"
 "}"
 "float p(vec3 v,vec2 i)"
 "{"
   "float y=length(v.xz);"
   "return max(dot(i,vec2(y,v.y)),v.y);"
 "}"
 "float t(in vec3 v,in vec4 y)"
 "{"
   "vec3 i=v-y.xyz;"
   "return length(i)-y.w;"
 "}"
 "vec3 r(vec3 v)"
 "{"
   "float y=cos(10.*v.y+10.),z=sin(10.*v.y+10.);"
   "mat2 i=mat2(y,-z,z,y);"
   "return vec3(i*v.xz,v.y);"
 "}"
 "float r(float v,float y)"
 "{"
   "float z=.06,i=clamp(.5+.5*(y-v)/z,0.,1.);"
   "return mix(y,v,i)-z*i*(1.-i);"
 "}"
 "float M(float v,float i,float y)"
 "{"
   "float z=clamp(.5+.5*(i-v)/y,0.,1.);"
   "return mix(i,v,z)-y*z*(1.-z);"
 "}"
 "vec2 w(vec2 v,vec2 y)"
 "{"
   "float z=1.6,i=clamp(.5+.5*(y.x-v.x)/z,0.,1.);"
   "return mix(y,v,i)-z*i*(1.-i);"
 "}"
 "float x(vec3 v,vec2 y)"
 "{"
   "return max(e(v.xz)-y.x,abs(v.y)-y.y);"
 "}\n"
 "#define MAT_NONE 0.0\n"
 "#define MAT_DBF 1.0\n"
 "#define MAT_GROUND 2.0\n"
 "#define MAT_TREE 3.0\n"
 "#define MAT_SNOW 4.0\n"
 "#define MAT_HAT 5.0\n"
 "#define MAT_EYE 6.0\n"
 "#define MAT_BODY 7.0\n"
 "#define MAT_NOSE 8.0\n"
 "#define MAT_ARM 9.0\n"
 "float c(vec2 v)"
 "{"
   "vec2 y=v*.05;"
   "v*=.06;"
   "v+=227.3;"
   "vec2 m=floor(v),f=fract(v);"
   "f=f*f*(3.-2.*f);"
   "float z=texture2D(iChannel0,(m+vec2(.5,.5))/256.,-32.).x,x=texture2D(iChannel0,(m+vec2(1.5,.5))/256.,-32.).x,e=texture2D(iChannel0,(m+vec2(.5,1.5))/256.,-32.).x,t=texture2D(iChannel0,(m+vec2(1.5,1.5))/256.,-32.).x,s=mix(mix(z,x,f.x),mix(e,t,f.x),f.y);"
   "s-=.04*p(5.*y);"
   "s-=sin(y).x;"
   "s+=sin(y).y;"
   "s-=sin(y*.3).x;"
   "s+=sin(y*.5).y;"
   "s=s*5.;"
   "float M=i(vec3(y,0.),vec3(1.,1.,1.)),r=smoothstep(.5,2.2,abs(y.y));"
   "s=mix(s,s-5.,r);"
   "float u=1.-smoothstep(.1,1.,abs(y.x));"
   "u*=smoothstep(.5,1.,abs(sin(y.y)));"
   "s=mix(s,s-5.,u);"
   "return s-.2;"
 "}"
 "vec2 h(in vec3 v)"
 "{"
   "float y=MAT_NONE;"
   "mat3 i=t(pi2*.25);"
   "v.y-=40.;"
   "float z=D(i*v,vec2(10.,3.2));"
   "z=min(z,D(v+vec3(-10.,-12.,0.),vec3(2.2,12.,2.2),1.));"
   "v.x-=28.;"
   "float m=D(v*i,vec2(10.,3.2));"
   "m=min(m,D(v+vec3(10.,-12.,0.),vec3(2.2,12.,2.2),1.));"
   "v.x-=28.;"
   "float r=D(v+vec3(10.,1.,0.),vec3(2.2,10.,2.2),1.);"
   "v+=vec3(0.,-9.,0.);"
   "r=min(r,D(i*v,vec2(10.,3.2)));"
   "r=f(r,n(v+vec3(-4.8,10.,1.),vec3(12.,10.,5.)));"
   "r=f(r,n(v+vec3(-14.8,-8.,1.),vec3(12.,10.,5.)));"
   "r=min(r,D(v+vec3(5.,7.5,0.),vec3(2.2,2.2,2.2),1.));"
   "float x=min(min(r,z),m);"
   "vec2 s=vec2(x,y);"
   "return s;"
 "}"
 "float c(vec3 v,float y)"
 "{"
   "float f=smoothstep(.4,.6,texture2D(iChannel1,.001*v.xz,-32.).x);"
   "f*=smoothstep(23.,24.,abs(v.z-3.));"
   "vec2 i=floor(v.xz/4.);"
   "v.xz=mod(v.xz,4.)-2.;"
   "v.xz+=3.*(-1.+2.*texture2D(iChannel2,i/256.,-32.).xy);"
   "float m=p(v-vec3(0.,y+6.*f,0.),vec2(.9397,.342));"
   "return m;"
 "}"
 "float h(vec3 v,float y)"
 "{"
   "float m=16.,f=smoothstep(.4,.6,texture2D(iChannel1,.001*v.xz,-32.).x);"
   "f*=smoothstep(1.,2.,abs(v.z-3.));"
   "vec2 i=floor(v.xz/4.);"
   "vec3 z=v;"
   "float s=smoothstep(.4,.6,texture2D(iChannel1,.011*v.xz,-32.).x);"
   "v.xz=mod(v.xz*vec2(.1,.1),4.)-2.;"
   "float r=p(v-vec3(0.,y+3.*f,0.),vec2(.9397,.642));"
   "z.xz=mod(z.xz*vec2(1.,1.),1.)-2.;"
   "float M=p(z-vec3(0.,y+3.*s,0.),vec2(9.9397,.2642));"
   "r=r*.4;"
   "return min(r,r);"
 "}"
 "vec3 y=normalize(vec3(-.5,.25,-.3));"
 "vec2 d(in vec3 v,in vec3 y)"
 "{"
   "mat3 z;"
   "float i=MAT_BODY;"
   "vec3 m=v;"
   "mat3 r=x(pi2*.5);"
   "r*=t(pi2*.75);"
   "float s=f(v)*.2,p=t(v-vec3(0.,20.,0.)+s+y,vec4(20.)),d=t(v-vec3(0.,20.,0.)+s+y,vec4(30.));"
   "if(d>10.)"
     "return vec2(1000.,0.);"
   "float n=t(v-vec3(10.,55.,10.)+s+y,vec4(10.));"
   "p=w(p,n,2.);"
   "float c=D((v-vec3(20.,75.,20.)+s+y)*t(0.),vec2(4.,4.));"
   "c=w(c,D((v-vec3(20.,73.,20.)+s+y)*t(0.),vec2(10.,1.)),2.);"
   "if(c<p)"
     "i=MAT_HAT;"
   "p=w(p,c,2.);"
   "float g=t(v-vec3(18.,65.,28.)+s+y,2.);"
   "if(g<p)"
     "i=MAT_NOSE;"
   "p=w(p,g,2.);"
   "float u=t(v-vec3(15.,68.,27.)+s+y,1.);"
   "u=min(u,t(v-vec3(22.,68.,27.)+s+y,1.));"
   "if(u<p)"
     "i=MAT_EYE;"
   "p=w(p,u,.2);"
   "z=M(pi2*.25)*t(pi2*.3);"
   "float a=e(v*z-(vec3(-2.,0.,30.)+y)*z,vec2(1.,5.));"
   "z=M(pi2*-.25)*t(pi2*.3);"
   "a=w(a,e(v*z-(vec3(40.,0.,30.)+y)*z,vec2(1.,5.)),1.);"
   "if(a<p)"
     "i=MAT_ARM;"
   "p=w(p,a,3.6);"
   "float S=t(v-vec3(18.,45.,36.5)+s+y,1.5);"
   "S=min(t(v-vec3(18.4,40.,37.)+s+y,1.5),S);"
   "S=min(t(v-vec3(18.,35.,37.5)+s+y,1.5),S);"
   "S=min(t(v-vec3(19.1,50.,33.5)+s+y,1.5),S);"
   "S=min(t(v-vec3(18.7,55.,31.)+s+y,1.5),S);"
   "if(S<p)"
     "i=MAT_NOSE;"
   "p=w(p,S,.5);"
   "vec2 l=vec2(p,i);"
   "return l;"
 "}"
 "vec2 d(in vec3 v)"
 "{"
   "vec2 f=vec2(1000.,-1.);"
   "float i=n(v-cube-vec3(2.,0.,0.),vec3(1.)),y=c(v.xz),z=v.y-y;"
   "f=vec2(z,0.);"
   "float m=100000.,x=h(v,y),r=c(v,y);"
   "m=min(x,x);"
   "f.x=min(m,f.x);"
   "f.y=MAT_SNOW;"
   "if(i<f.x)"
     "f.x=i,f.y=MAT_ARM;"
   "return f;"
 "}"
 "vec3 a(in vec3 i,in vec3 y)"
 "{"
   "float z=500.,f=v*1.5,r=0.,m=0.,x=1.;"
   "for(int s=0;s<150;s++)"
     "{"
       "if(abs(f)<v||r>z)"
         "continue;"
       "r+=f;"
       "vec2 M=d(i+y*r);"
       "f=M.x;"
       "m=M.y;"
       "x=M.y;"
     "}"
   "if(r>z)"
     "x=-1.;"
   "return vec3(r,m,x);"
 "}"
 "vec3 a(in vec3 y)"
 "{"
   "vec3 m=vec3(v,0.,0.);"
   "return normalize(vec3(d(y+m.xyy).x-d(y-m.xyy).x,d(y+m.yxy).x-d(y-m.yxy).x,d(y+m.yyx).x-d(y-m.yyx).x));"
 "}"
 "float a(in vec3 v,in vec3 y,float i)"
 "{"
   "float z=1.,f=0.,m=1.;"
   "for(int r=0;r<60;r++)"
     "m=d(v+y*f).x,z=min(z,i*m/f),f+=clamp(m,.02,1.);"
   "return clamp(z,0.,1.);"
 "}"
 "float g(in vec3 v,in vec3 y)"
 "{"
   "float f=0.;"
   "for(int i=0;i<8;i++)"
     "{"
       "float m=.1+1.5*pow(float(i)/8.,2.);"
       "vec3 z=v+y*m;"
       "float s=d(z).x;"
       "f+=max(0.,m-3.*s-.01);"
     "}"
   "return clamp(1.-.15*f,0.,1.);"
 "}"
 "void D(in vec3 v,in vec3 z,in vec3 m,in float f,out vec3 r,out vec4 s,out vec2 x)"
 "{"
   "r=vec3(0.);"
   "s=vec4(0.);"
   "x=vec2(0.);"
   "if(f==MAT_HAT)"
     "{"
       "s.xyz=vec3(.2,.4,.2);"
       "float p=smoothstep(.2,.5,z.y);"
       "vec3 e=vec3(.65,.8,.8),g=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
       "g.y=abs(g.y);"
       "float M=max(0.,pow(clamp(dot(y,reflect(m,g)),0.,1.),16.));"
       "x.y=M*p;"
       "s.xyz=mix(s.xyz,e,p);"
     "}"
   "else"
     " if(f==MAT_BODY)"
       "{"
         "s.xyz=vec3(.8,.8,.8)*.5;"
         "float p=smoothstep(.2,.5,z.y);"
         "vec3 e=vec3(.65,.8,.8),g=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
         "g.y=abs(g.y);"
         "float M=max(0.,pow(clamp(dot(y,reflect(m,g)),0.,1.),16.));"
         "x.y=M*p;"
         "s.xyz=mix(s.xyz,e,p);"
       "}"
     "else"
       " if(f==MAT_NOSE)"
         "{"
           "s.xyz=vec3(.2,.15,.1);"
           "float p=smoothstep(.2,.9,z.y);"
           "p=mix(p,.2,.75*smoothstep(.9,1.,i(iChannel1,.1*v,z).x));"
           "vec3 e=vec3(.65,.8,.8),g=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
           "g.y=abs(g.y);"
           "float M=max(0.,pow(clamp(dot(y,reflect(m,g)),0.,1.),16.));"
           "s.y=M*p;"
           "s.xyz=mix(s.xyz,e,p);"
         "}"
       "else"
         " if(f==MAT_EYE)"
           "{"
             "s.xyz=vec3(.1,.1,.1);"
             "float p=smoothstep(.2,.9,z.y);"
             "vec3 e=vec3(.65,.8,.8),g=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
             "g.y=abs(g.y);"
             "float M=max(0.,pow(clamp(dot(y,reflect(m,g)),0.,1.),16.));"
             "s.y=M*p;"
             "s.xyz=mix(s.xyz,e,p*.5);"
           "}"
         "else"
           " if(f==MAT_SNOW)"
             "{"
               "s.xyz=vec3(.1,.1,.1);"
               "float p=smoothstep(.2,.5,z.y);"
               "vec3 e=vec3(.65,.8,.8),g=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
               "g.y=abs(g.y);"
               "float M=max(0.,pow(clamp(dot(y,reflect(m,g)),0.,1.),16.));"
               "s.y=M*p;"
               "s.xyz=mix(s.xyz,e,p*.5);"
             "}"
           "else"
             " if(f==MAT_ARM)"
               "{"
                 "s.xyz=vec3(.4,.25,.2);"
                 "float p=smoothstep(.2,.5,z.y);"
                 "vec3 e=vec3(.65,.8,.8),g=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
                 "g.y=abs(g.y);"
                 "float M=max(0.,pow(clamp(dot(y,reflect(m,g)),0.,1.),16.));"
                 "s.y=M*p;"
                 "s.xyz=mix(s.xyz,e,p*.5);"
               "}"
 "}"
 "float g(in vec3 v)"
 "{"
   "vec2 m=v.xz+y.xz*(100.-v.y)/y.y;"
   "float z=.1+.9*smoothstep(.1,.35,texture2D(iChannel1,.0003*m+.1+.013*iGlobalTime).x);"
   "return z;"
 "}"
 "vec3 l(vec3 v,vec3 y)"
 "{"
   "return vec3(1.,1.,1.);"
 "}"
 "void main()"
 "{"
   "vec2 v=vec2(0.,0.),f=-1.+2.*gl_FragCoord.xy/m.xy,z=f*vec2(1.75,1.);"
   "float i=iGlobalTime*.15+2.*v.x/m.x;"
   "vec3 s=cameraPosition,p=normalize(viewDirection);"
   "float M=iGlobalTime;"
   "vec3 r=2.5*vec3(.08,.13,.15)-p.y*.5;"
   "r*=.9;"
   "float e=clamp(dot(p,y),0.,1.);"
   "vec3 x=r,d=a(s,p);"
   "float c=1.;"
   "if(d.z>-.5)"
     "{"
       "vec3 S=s+d.x*p,t=a(S);"
       "vec4 n=vec4(0.);"
       "vec2 u=vec2(0.);"
       "vec3 l=vec3(0.);"
       "D(S,t,p,d.z,l,n,u);"
       "t=normalize(t+l);"
       "vec3 w=reflect(p,t);"
       "float E=g(S,t)*clamp(.7+.3*t.y,0.,1.),o=.6+.4*t.y,j=clamp(-t.y,0.,1.),h=max(dot(t,y),0.),T=max(.2+.8*dot(t,normalize(vec3(-y.x,0.,-y.z))),0.),Y=0.;"
       "if(h>.01)"
         "Y=a(S+.01*t,y,64.);"
       "Y*=g(S);"
       "float A=pow(clamp(1.+dot(t,p),0.,1.),3.);"
       "vec3 W=vec3(0.);"
       "W+=h*vec3(1.7,1.15,.7)*pow(vec3(Y),vec3(1.,1.2,2.));"
       "W+=o*vec3(.05,.2,.45)*E;"
       "W+=T*vec3(.2,.25,.25)*E;"
       "W+=1.2*j*vec3(.15,.2,.2)*(.5+.5*E);"
       "W+=A*vec3(1.,1.25,1.3)*E*.5*(.5+.5*h*Y);"
       "W+=u.y*vec3(1.,.6,.5)*4.*E*h*(.1+.9*Y);"
       "r=n.xyz*W;"
       "r=mix(x,r,exp(-.0015*pow(d.x,1.)));"
       "vec4 b=mviewproj*vec4(S,1.);"
       "float C=b.z,O=b.w;"
       "c=C/O;"
       "c=(c+1.)/2.;"
     "}"
   "r+=vec3(1.,.6,.2)*.4*pow(e,4.);"
   "r=pow(clamp(r,0.,1.),vec3(.45));"
   "gl_FragDepth=c;"
   "gl_FragColor=vec4(vec3(r),1.);"
 "}";

const char *terrain_vert =
 "varying vec2 uv;"
 "varying vec3 cameraPosition,viewDirection;"
 "uniform mat4 modelviewMatrix,imvm;"
 "varying mat4 pmat,mview;"
 "varying float nearPlane,farPlane;"
 "void main()"
 "{"
   "uv=gl_Vertex.xy;"
   "gl_Position=gl_Vertex;"
   "vec4 v=gl_Vertex;"
   "v=gl_ProjectionMatrixInverse*v;"
   "v/=v.w;"
   "v=gl_ModelViewMatrixInverse*v;"
   "vec4 i=v;"
   "mview=gl_ModelViewMatrix;"
   "pmat=gl_ModelViewProjectionMatrix;"
   "nearPlane=-(gl_ProjectionMatrix[3][2]/(gl_ProjectionMatrix[2][2]-1.));"
   "farPlane=-(gl_ProjectionMatrix[3][2]/(gl_ProjectionMatrix[2][2]+1.));"
   "cameraPosition=(gl_ModelViewMatrixInverse*vec4(0.,0.,0.,1.)).xyz;"
   "viewDirection=normalize(i.xyz*i.w-cameraPosition).xyz;"
 "}";

const char *terrain_frag =
 "varying vec2 uv;"
 "uniform float iGlobalTime;"
 "uniform sampler2D iChannel0,iChannel1,iChannel2;"
 "varying mat4 mview;"
 "varying float znear,zfar,nearPlane,farPlane;"
 "uniform mat4 mvm,imvm;"
 "varying mat4 pmat;"
 "uniform vec3 cubePos;"
 "varying vec3 cameraPosition;"
 "varying float nearPlanePosition;"
 "varying vec3 viewDirection;\n"
 "#define pi2 6.28318530718\n"
 "const float v=.015;"
 "vec2 m=vec2(800.,600.);struct hitInfo{int materialId;};"
 "float i(float v)"
 "{"
   "return fract(sin(v)*43758.5);"
 "}"
 "float p(in vec3 v)"
 "{"
   "vec3 m=floor(v),y=fract(v);"
   "\n#if 0\n"
   "y=y*y*(3.-2.*y);"
   "float z=m.x+m.y*57.+113.*m.z;"
   "return mix(mix(mix(i(z),i(z+1.),y.x),mix(i(z+57.),i(z+58.),y.x),y.y),mix(mix(i(z+113.),i(z+114.),y.x),mix(i(z+170.),i(z+171.),y.x),y.y),y.z);"
 "}"
 "const mat3 y=mat3(0.,.8,.6,-.8,.36,-.48,-.6,-.48,.64);"
 "float x(in vec2 v)"
 "{"
   "vec2 m=floor(v),y=fract(v),i=m.xy+y.xy*y.xy*(3.-2.*y.xy);"
   "return-1.+2.*texture2D(iChannel0,(i+.5)/256.,-100.).x;"
 "}"
 "vec3 i(sampler2D v,vec3 y,vec3 i)"
 "{"
   "vec3 m=texture2D(v,y.yz).xyz,z=texture2D(v,y.zx).xyz,f=texture2D(v,y.xy).xyz;"
   "return m*abs(i.x)+z*abs(i.y)+f*abs(i.z);"
 "}"
 "float s(vec3 v)"
 "{"
   "float f;"
   "f=.5*x(v);"
   "v=y*v*2.02;"
   "f+=.25*x(v);"
   "v=y*v*2.03;"
   "f+=.125*x(v);"
   "v=y*v*2.01;"
   "f+=.0625*x(v);"
   "return f;"
 "}"
 "mat3 n(in float v)"
 "{"
   "float i=cos(v),y=sin(v);"
   "return mat3(i,y,0.,-y,i,0.,0.,0.,1.);"
 "}"
 "mat3 t(in float v)"
 "{"
   "float y=cos(v),z=sin(v);"
   "return mat3(1.,0.,0.,0.,y,-z,0.,z,y);"
 "}"
 "mat3 f(in float v)"
 "{"
   "float y=cos(v),z=sin(v);"
   "return mat3(y,0.,z,0.,1.,0.,-z,0.,y);"
 "}"
 "vec2 f(vec2 v,vec2 y)"
 "{"
   "return v.x<y.x?v:y;"
 "}"
 "float i(float v,float y)"
 "{"
   "return max(-y,v);"
 "}"
 "vec3 n(vec3 v,vec3 y)"
 "{"
   "return mod(v,y)-.5*y;"
 "}"
 "float e(vec2 v)"
 "{"
   "return sqrt(v.x*v.x+v.y*v.y);"
 "}"
 "float D(vec2 v)"
 "{"
   "return v=v*v*v,v=v*v,pow(v.x+v.y,1./6.);"
 "}"
 "float M(vec2 v)"
 "{"
   "return v=v*v,v=v*v,v=v*v,pow(v.x+v.y,.125);"
 "}"
 "float D(vec3 v,vec2 y)"
 "{"
   "vec2 i=vec2(e(v.xz)-y.x,v.y);"
   "return M(i)-y.y;"
 "}"
 "float M(vec3 v,vec2 y)"
 "{"
   "return max(length(v.xz)-y.x,abs(v.y)-y.y);"
 "}"
 "float D(vec3 v,vec3 y,float z)"
 "{"
   "return length(max(abs(v)-y,0.))-z;"
 "}"
 "float e(vec3 v,vec3 y)"
 "{"
   "vec3 i=abs(v)-y;"
   "return min(max(i.x,max(i.y,i.z)),0.)+length(max(i,0.));"
 "}"
 "float p(vec3 v,vec2 y)"
 "{"
   "float i=length(v.xz);"
   "return max(dot(y,vec2(i,v.y)),v.y);"
 "}"
 "float s(in vec3 v,in vec4 y)"
 "{"
   "vec3 i=v-y.xyz;"
   "return length(i)-y.w;"
 "}"
 "float t(float v,float y)"
 "{"
   "float z=.06,i=clamp(.5+.5*(y-v)/z,0.,1.);"
   "return mix(y,v,i)-z*i*(1.-i);"
 "}"
 "float M(float v,float i,float y)"
 "{"
   "float z=clamp(.5+.5*(i-v)/y,0.,1.);"
   "return mix(i,v,z)-y*z*(1.-z);"
 "}"
 "vec2 x(vec2 v,vec2 y)"
 "{"
   "float z=1.6,i=clamp(.5+.5*(y.x-v.x)/z,0.,1.);"
   "return mix(y,v,i)-z*i*(1.-i);"
 "}"
 "float w(vec3 v,vec2 y)"
 "{"
   "return max(D(v.xz)-y.x,abs(v.y)-y.y);"
 "}\n"
 "#define MAT_NONE 0.0\n"
 "#define MAT_DBF 1.0\n"
 "#define MAT_GROUND 2.0\n"
 "#define MAT_TREE 3.0\n"
 "#define MAT_SNOW 4.0\n"
 "#define MAT_HAT 5.0\n"
 "#define MAT_EYE 6.0\n"
 "#define MAT_BODY 7.0\n"
 "#define MAT_NOSE 8.0\n"
 "#define MAT_ARM 9.0\n"
 "float w(vec2 v)"
 "{"
   "vec2 y=v*.05;"
   "v*=.06;"
   "v+=227.3;"
   "vec2 i=floor(v),f=fract(v);"
   "f=f*f*(3.-2.*f);"
   "float z=texture2D(iChannel0,(i+vec2(.5,.5))/256.,-32.).x,m=texture2D(iChannel0,(i+vec2(1.5,.5))/256.,-32.).x,p=texture2D(iChannel0,(i+vec2(.5,1.5))/256.,-32.).x,r=texture2D(iChannel0,(i+vec2(1.5,1.5))/256.,-32.).x,s=mix(mix(z,m,f.x),mix(p,r,f.x),f.y);"
   "s-=.04*x(5.*y);"
   "s-=sin(y).x;"
   "s+=sin(y).y;"
   "s=s*5.+5.;"
   "float M=n(vec3(y,0.),vec3(1.,1.,1.)),g=smoothstep(.5,2.2,abs(y.y));"
   "s=mix(s,s-5.,g);"
   "float e=1.-smoothstep(.1,1.,abs(y.x));"
   "e*=smoothstep(.5,1.,abs(sin(y.y)));"
   "s=mix(s,s-5.,e);"
   "return s;"
 "}"
 "vec2 r(in vec3 v)"
 "{"
   "float y=MAT_NONE;"
   "mat3 z=t(pi2*.25);"
   "v.y-=40.;"
   "float f=D(z*v,vec2(10.,3.2));"
   "f=min(f,D(v+vec3(-10.,-12.,0.),vec3(2.2,12.,2.2),1.));"
   "v.x-=28.;"
   "float m=D(v*z,vec2(10.,3.2));"
   "m=min(m,D(v+vec3(10.,-12.,0.),vec3(2.2,12.,2.2),1.));"
   "v.x-=28.;"
   "float r=D(v+vec3(10.,1.,0.),vec3(2.2,10.,2.2),1.);"
   "v+=vec3(0.,-9.,0.);"
   "r=min(r,D(z*v,vec2(10.,3.2)));"
   "r=i(r,e(v+vec3(-4.8,10.,1.),vec3(12.,10.,5.)));"
   "r=i(r,e(v+vec3(-14.8,-8.,1.),vec3(12.,10.,5.)));"
   "r=min(r,D(v+vec3(5.,7.5,0.),vec3(2.2,2.2,2.2),1.));"
   "float p=min(min(r,f),m);"
   "vec2 n=vec2(p,y);"
   "return n;"
 "}"
 "float r(vec3 v,float y)"
 "{"
   "float f=smoothstep(.4,.6,texture2D(iChannel1,.001*v.xz,-32.).x);"
   "f*=smoothstep(23.,24.,abs(v.z-3.));"
   "vec2 i=floor(v.xz/4.);"
   "v.xz=mod(v.xz,4.)-2.;"
   "v.xz+=3.*(-1.+2.*texture2D(iChannel2,i/256.,-32.).xy);"
   "float e=p(v-vec3(0.,y+6.*f,0.),vec2(.9397,.342));"
   "return e;"
 "}"
 "float c(vec3 v,float y)"
 "{"
   "float m=16.,f=smoothstep(.4,.6,texture2D(iChannel1,.001*v.xz,-32.).x);"
   "f*=smoothstep(1.,2.,abs(v.z-3.));"
   "vec2 z=floor(v.xz/4.);"
   "vec3 i=v;"
   "float x=smoothstep(.4,.6,texture2D(iChannel1,.011*v.xz,-32.).x);"
   "v.xz=mod(v.xz*vec2(.1,.1),4.)-2.;"
   "float r=p(v-vec3(0.,y+3.*f,0.),vec2(.9397,.642));"
   "i.xz=mod(i.xz*vec2(1.,1.),1.)-2.;"
   "float M=p(i-vec3(0.,y+3.*x,0.),vec2(9.9397,.2642));"
   "return min(r,r);"
 "}"
 "vec3 z=normalize(vec3(-.5,.25,-.3));"
 "vec2 h(in vec3 v,in vec3 y)"
 "{"
   "mat3 z;"
   "float i=MAT_BODY;"
   "vec3 m=v;"
   "mat3 r=n(pi2*.5);"
   "r*=t(pi2*.75);"
   "float p=s(v)*.2,g=s(v-vec3(0.,20.,0.)+p+y,vec4(20.)),e=s(v-vec3(10.,55.,10.)+p+y,vec4(10.));"
   "g=x(g,e,2.);"
   "float c=D((v-vec3(20.,75.,20.)+p+y)*t(0.),vec2(4.,4.));"
   "c=x(c,D((v-vec3(20.,73.,20.)+p+y)*t(0.),vec2(10.,1.)),2.);"
   "if(c<g)"
     "i=MAT_HAT;"
   "g=x(g,c,2.);"
   "float d=s(v-vec3(18.,65.,28.)+p+y,2.);"
   "if(d<g)"
     "i=MAT_NOSE;"
   "g=x(g,d,2.);"
   "float S=s(v-vec3(15.,68.,27.)+p+y,1.);"
   "S=min(S,s(v-vec3(22.,68.,27.)+p+y,1.));"
   "if(S<g)"
     "i=MAT_EYE;"
   "g=x(g,S,.2);"
   "z=f(pi2*.25)*t(pi2*.3);"
   "float u=M(v*z-(vec3(-2.,0.,30.)+y)*z,vec2(1.,5.));"
   "z=f(pi2*-.25)*t(pi2*.3);"
   "u=x(u,M(v*z-(vec3(40.,0.,30.)+y)*z,vec2(1.,5.)),1.);"
   "if(u<g)"
     "i=MAT_ARM;"
   "g=x(g,u,3.6);"
   "float a=s(v-vec3(18.,45.,36.5)+p+y,1.5);"
   "a=min(s(v-vec3(18.4,40.,37.5)+p+y,1.5),a);"
   "a=min(s(v-vec3(18.,35.,37.5)+p+y,1.5),a);"
   "a=min(s(v-vec3(19.1,50.,33.5)+p+y,1.5),a);"
   "a=min(s(v-vec3(18.7,55.,31.)+p+y,1.5),a);"
   "if(a<g)"
     "i=MAT_NOSE;"
   "g=x(g,a,2.);"
   "vec2 o=vec2(g,i);"
   "return o;"
 "}"
 "vec2 c(in vec3 v)"
 "{"
   "vec2 f=vec2(1000.,-1.);"
   "float y=w(v.xz),i=v.y-y;"
   "f=vec2(i,0.);"
   "float z=100000.,m=c(v,y);"
   "z=min(m,m);"
   "f.x=min(z,f.x);"
   "f.y=MAT_SNOW;"
   "return f;"
 "}"
 "vec3 a(in vec3 i,in vec3 y)"
 "{"
   "float z=250.,f=v*1.5,r=0.,m=0.,p=1.;"
   "for(int s=0;s<150;s++)"
     "{"
       "if(abs(f)<v||r>z)"
         "continue;"
       "r+=f;"
       "vec2 M=c(i+y*r);"
       "f=M.x;"
       "m=M.y;"
       "p=M.y;"
     "}"
   "if(r>z)"
     "p=-1.;"
   "return vec3(r,m,p);"
 "}"
 "vec3 a(in vec3 y)"
 "{"
   "vec3 m=vec3(v,0.,0.);"
   "return normalize(vec3(c(y+m.xyy).x-c(y-m.xyy).x,c(y+m.yxy).x-c(y-m.yxy).x,c(y+m.yyx).x-c(y-m.yyx).x));"
 "}"
 "float a(in vec3 v,in vec3 y,float z)"
 "{"
   "float i=1.,f=0.,m=1.;"
   "for(int r=0;r<60;r++)"
     "m=c(v+y*f).x,i=min(i,z*m/f),f+=clamp(m,.02,1.);"
   "return clamp(i,0.,1.);"
 "}"
 "float g(in vec3 v,in vec3 y)"
 "{"
   "float f=0.;"
   "for(int i=0;i<8;i++)"
     "{"
       "float z=.1+1.5*pow(float(i)/8.,2.);"
       "vec3 m=v+y*z;"
       "float s=c(m).x;"
       "f+=max(0.,z-3.*s-.01);"
     "}"
   "return clamp(1.-.15*f,0.,1.);"
 "}"
 "void D(in vec3 v,in vec3 y,in vec3 m,in float f,out vec3 r,out vec4 s,out vec2 g)"
 "{"
   "r=vec3(0.);"
   "s=vec4(0.);"
   "g=vec2(0.);"
   "if(f==MAT_HAT)"
     "{"
       "s.xyz=vec3(.2,.4,.2);"
       "float p=smoothstep(.2,.5,y.y);"
       "vec3 x=vec3(.65,.8,.8),e=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
       "e.y=abs(e.y);"
       "float M=max(0.,pow(clamp(dot(z,reflect(m,e)),0.,1.),16.));"
       "g.y=M*p;"
       "s.xyz=mix(s.xyz,x,p);"
     "}"
   "else"
     " if(f==MAT_BODY)"
       "{"
         "s.xyz=vec3(.8,.8,.8)*.5;"
         "float p=smoothstep(.2,.5,y.y);"
         "vec3 x=vec3(.65,.8,.8),e=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
         "e.y=abs(e.y);"
         "float M=max(0.,pow(clamp(dot(z,reflect(m,e)),0.,1.),16.));"
         "g.y=M*p;"
         "s.xyz=mix(s.xyz,x,p);"
       "}"
     "else"
       " if(f==MAT_NOSE)"
         "{"
           "s.xyz=vec3(.2,.15,.1);"
           "float p=smoothstep(.2,.9,y.y);"
           "p=mix(p,.2,.75*smoothstep(.9,1.,i(iChannel1,.1*v,y).x));"
           "vec3 x=vec3(.65,.8,.8),e=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
           "e.y=abs(e.y);"
           "float M=max(0.,pow(clamp(dot(z,reflect(m,e)),0.,1.),16.));"
           "s.y=M*p;"
           "s.xyz=mix(s.xyz,x,p);"
         "}"
       "else"
         " if(f==MAT_EYE)"
           "{"
             "s.xyz=vec3(.1,.1,.1);"
             "float p=smoothstep(.2,.9,y.y);"
             "vec3 x=vec3(.65,.8,.8),e=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
             "e.y=abs(e.y);"
             "float M=max(0.,pow(clamp(dot(z,reflect(m,e)),0.,1.),16.));"
             "s.y=M*p;"
             "s.xyz=mix(s.xyz,x,p*.5);"
           "}"
         "else"
           " if(f==MAT_SNOW)"
             "{"
               "s.xyz=vec3(.1,.1,.1);"
               "float p=smoothstep(.2,.5,y.y);"
               "vec3 x=vec3(.65,.8,.8),e=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
               "e.y=abs(e.y);"
               "float M=max(0.,pow(clamp(dot(z,reflect(m,e)),0.,1.),16.));"
               "s.y=M*p;"
               "s.xyz=mix(s.xyz,x,p*.5);"
             "}"
           "else"
             " if(f==MAT_ARM)"
               "{"
                 "s.xyz=vec3(.4,.25,.2);"
                 "float p=smoothstep(.2,.5,y.y);"
                 "vec3 x=vec3(.65,.8,.8),e=normalize(-1.+2.*texture2D(iChannel0,.65*v.xz).xyz);"
                 "e.y=abs(e.y);"
                 "float M=max(0.,pow(clamp(dot(z,reflect(m,e)),0.,1.),16.));"
                 "s.y=M*p;"
                 "s.xyz=mix(s.xyz,x,p*.5);"
               "}"
 "}"
 "float g(in vec3 v)"
 "{"
   "vec2 y=v.xz+z.xz*(100.-v.y)/z.y;"
   "float m=.1+.9*smoothstep(.1,.35,texture2D(iChannel1,.0003*y+.1+.013*iGlobalTime).x);"
   "return m;"
 "}"
 "vec3 d(vec3 v,vec3 y)"
 "{"
   "return vec3(1.,1.,1.);"
 "}"
 "void main()"
 "{"
   "vec2 v=vec2(0.,0.),y=-1.+2.*gl_FragCoord.xy/m.xy,i=y*vec2(1.75,1.);"
   "float f=iGlobalTime*.15+2.*v.x/m.x;"
   "vec3 s=cameraPosition,p=normalize(viewDirection);"
   "float M=iGlobalTime;"
   "vec3 r=2.5*vec3(.08,.13,.15)-p.y*.5;"
   "r*=.9;"
   "float x=clamp(dot(p,z),0.,1.);"
   "vec3 e=r,d=a(s,p);"
   "float n=1.;"
   "if(d.z>-.5)"
     "{"
       "vec3 c=s+d.x*p,t=a(c);"
       "vec4 u=vec4(0.);"
       "vec2 S=vec2(0.);"
       "vec3 l=vec3(0.);"
       "D(c,t,p,d.z,l,u,S);"
       "t=normalize(t+l);"
       "vec3 w=reflect(p,t);"
       "float E=g(c,t)*clamp(.7+.3*t.y,0.,1.),o=.6+.4*t.y,h=clamp(-t.y,0.,1.),Y=max(dot(t,z),0.),j=max(.2+.8*dot(t,normalize(vec3(-z.x,0.,-z.z))),0.),W=0.;"
       "if(Y>.01)"
         "W=a(c+.01*t,z,64.);"
       "W*=g(c);"
       "float A=pow(clamp(1.+dot(t,p),0.,1.),3.);"
       "vec3 T=vec3(0.);"
       "T+=Y*vec3(1.7,1.15,.7)*pow(vec3(W),vec3(1.,1.2,2.));"
       "T+=o*vec3(.05,.2,.45)*E;"
       "T+=j*vec3(.2,.25,.25)*E;"
       "T+=1.2*h*vec3(.15,.2,.2)*(.5+.5*E);"
       "T+=A*vec3(1.,1.25,1.3)*E*.5*(.5+.5*Y*W);"
       "T+=S.y*vec3(1.,.6,.5)*4.*E*Y*(.1+.9*W);"
       "r=u.xyz*T;"
       "r=mix(e,r,exp(-.0015*pow(d.x,1.)));"
       "vec4 b=vec4(c-cameraPosition,1.),O=pmat*b;"
       "float C=dot(c-cameraPosition,p),P=(farPlane+nearPlane)/(farPlane-nearPlane),N=2.*farPlane*nearPlane/(farPlane-nearPlane),R=P+N/C;"
       "n=R;"
     "}"
   "r+=vec3(1.,.6,.2)*.4*pow(x,4.);"
   "r=pow(clamp(r,0.,1.),vec3(.45));"
   "gl_FragDepth=n;"
   "gl_FragColor=vec4(vec3(r),1.);"
 "}";

const char *perlin2d_fs_glsl =
 "vec3 v(vec3 v)"
 "{"
   "return v-floor(v*(1./289.))*289.;"
 "}"
 "vec2 m(vec2 v)"
 "{"
   "return v-floor(v*(1./289.))*289.;"
 "}"
 "vec3 i(vec3 v)"
 "{"
   "return m((v*34.+1.)*v);"
 "}"
 "float x(vec2 v)"
 "{"
   "const vec4 y=vec4(.211325,.366025,-.57735,.0243902);"
   "vec2 z=floor(v+dot(v,y.yy)),f=v-z+dot(z,y.xx),s;"
   "s=f.x>f.y?vec2(1.,0.):vec2(0.,1.);"
   "vec4 r=f.xyxy+y.xxzz;"
   "r.xy-=s;"
   "z=m(z);"
   "vec3 p=i(i(z.y+vec3(0.,s.y,1.))+z.x+vec3(0.,s.x,1.)),x=max(.5-vec3(dot(f,f),dot(r.xy,r.xy),dot(r.zw,r.zw)),0.);"
   "x=x*x;"
   "x=x*x;"
   "vec3 M=2.*fract(p*y.www)-1.,e=abs(M)-.5,g=floor(M+.5),t=M-g;"
   "x*=1.79284-.853735*(t*t+e*e);"
   "vec3 u;"
   "u.x=t.x*f.x+e.x*f.y;"
   "u.yz=t.yz*r.xz+e.yz*r.yw;"
   "return 130.*dot(x,u);"
 "}"
 "float p(vec2 v)"
 "{"
   "return fract(sin(dot(v.xy,vec2(12.9898,78.233)))*43758.5);"
 "}"
 "float t(float v)"
 "{"
   "return fract(sin(v)*43758.5);"
 "}"
 "float f(vec2 v)"
 "{"
   "return fract(cos(dot(v,vec2(12.9898,4.1414)))*43758.5);"
 "}"
 "float y(vec2 v)"
 "{"
   "const vec2 y=vec2(0.,1.);"
   "vec2 i=floor(v),z=smoothstep(vec2(0.),vec2(1.),fract(v));"
   "return mix(mix(f(i),f(i+y.yx),z.x),mix(f(i+y.xy),f(i+y.yy),z.x),z.y);"
 "}"
 "float n(vec2 v)"
 "{"
   "float z=0.,i=1.;"
   "for(int f=0;f<4;f++)"
     "z+=y(v)*i,v+=v,i*=.5;"
   "return z;"
 "}"
 "void main()"
 "{"
   "vec2 v=gl_FragCoord.xy/vec2(256.,256.),i=-1.+2.*v;"
   "i.x*=1.;"
   "gl_FragColor=vec4(y(i*256+32.),y(i*256+64.),y(i*256+128.),y(i*256+256.));"
 "}";

const char *particles_vert =
 "#version 330\n"
 "layout(location=0)in vec4 position;"
 "layout(location=1)in vec2 index;"
 "void main()"
 "{"
   "gl_Position=position;"
 "}";

const char *particles_geom =
 "#version 330\n"
 "float v(vec2 v)"
 "{"
   "return fract(sin(dot(v.xy,vec2(12.9898,78.233)))*43758.5);"
 "}"
 "float i(vec2 y)"
 "{"
   "float i=v(y+vec2(71.3,56.4)),z=v(y+vec2(32.9,28.5));"
   "return.03+sqrt(-2.*log(i*.999+.001))*cos(6.28319*z);"
 "}"
 "vec3 i(vec2 v,float y)"
 "{"
   "return vec3(i(v+vec2(19.412+y*.981,11.183+y*1.5677)),i(v+vec2(86.287+y*4.6671,87.242+y*8.6112)),i(v+vec2(37.563+y*3.367,23.543+y*5.729)));"
 "}\n"
 "#define pi2 6.28318530718\n"
 "layout(points)in;layout(triangle_strip,max_vertices=4)out;"
 "out vec2 quadCoord;"
 "uniform mat4 modelViewMatrix,projectionMatrix;"
 "uniform float fTime;"
 "uniform vec3 eye,rot;"
 "mat3 m(in float v)"
 "{"
   "float i=cos(v),y=sin(v);"
   "return mat3(i,y,0.,-y,i,0.,0.,0.,1.);"
 "}"
 "mat3 s(in float v)"
 "{"
   "float y=cos(v),z=sin(v);"
   "return mat3(1.,0.,0.,0.,y,-z,0.,z,y);"
 "}"
 "mat3 f(in float v)"
 "{"
   "float y=cos(v),z=sin(v);"
   "return mat3(y,0.,z,0.,1.,0.,-z,0.,y);"
 "}\n"
 "#define DEG_PER_RAD 0.0174532925\n"
 "void main()"
 "{"
   "vec3 y=vec3(.05,0.,-.05)*.5;"
   "vec4 i=gl_in[0].gl_Position;"
   "vec3 z=vec3(v(i.xy+vec2(23.098,47.863)),v(i.xy+vec2(98.672,38.942)),v(i.xy+vec2(86.573,24.182)));"
   "vec4 r=vec4(0.,1.,-.75,1.);"
   "r.xyz+=z*i.xyz;"
   "i.xyz=z;"
   "mat3 p=s(-pi2*(rot.x/360.));"
   "p*=f(-pi2*(rot.y/360.));"
   "p*=m(-pi2*(rot.z/360.));"
   "i*=modelViewMatrix;"
   "i.xyz+=eye*.01;"
   "i.xyz-=fTime*.05*r.xyz*p;"
   "i.xyz=mod(i.xyz,1.);"
   "i.xyz-=.5;"
   "i.xyz*=16.;"
   "i.w=1.;"
   "float M=.4;"
   "y*=M;"
   "if(M>.1)"
     "gl_Position=projectionMatrix*(i+y.xzyy),quadCoord=vec2(1.,-1.),EmitVertex(),gl_Position=projectionMatrix*(i+y.xxyy),quadCoord=vec2(1.,1.),EmitVertex(),gl_Position=projectionMatrix*(i+y.zzyy),quadCoord=vec2(-1.,-1.),EmitVertex(),gl_Position=projectionMatrix*(i+y.zxyy),quadCoord=vec2(-1.,1.),EmitVertex();"
 "}";

const char *particles_frag =
 "#version 330\n"
 "in vec2 quadCoord;"
 "void main()"
 "{"
   "float v=length(quadCoord),y=max(v-.2,0.),i=exp(-y*y*4.);"
   "if(i<.001)"
     "discard;"
   "gl_FragData[0]=vec4(1.);"
   "gl_FragData[0]=vec4(vec3(1.),i*.7);"
 "}";

const char *Noise3DLinear_frag =
 "uniform sampler2D t;"
 "uniform int textureLayer;"
 "float v(float v)"
 "{"
   "return fract(sin(v)*43758.5);"
 "}"
 "float m(in vec3 v)"
 "{"
   "vec2 i=texture2D(t,v.xy,-100.).yx;"
   "return mix(i.x,i.y,v.z);"
 "}"
 "void main()"
 "{"
   "vec2 v=vec2(800.,600.),i=gl_FragCoord.xy/v;"
   "gl_FragData[0].x=m(vec3(i,textureLayer/255.));"
 "}";

const char *blit_vert =
 "void main()"
 "{"
   "gl_Position=gl_Vertex;"
 "}";

const char *blit_frag =
 "uniform sampler2D t;"
 "void main()"
 "{"
   "vec2 v=gl_FragCoord.xy/vec2(800.,600.);"
   "gl_FragColor=vec4(texture2D(t,v).xyz,1.);"
 "}";

#endif // SHADER_CODER_INTRO_H_
